// MARK: - Generated Python Completions
// Generated from Python 3.13 documentation using inspect.getdoc()
// Generated on: 2025-11-26T17:22:10.432558

    // MARK: - Built-in Functions
    private static let builtinFunctions: [CompletionItem] = [
        .function(name: "abs", parameters: ["x"], documentation: "Return the absolute value of the argument."),
        .function(name: "all", parameters: ["iterable"], documentation: "Return True if bool(x) is True for all values x in the iterable."),
        .function(name: "any", parameters: ["iterable"], documentation: "Return True if bool(x) is True for any x in the iterable."),
        .function(name: "ascii", parameters: ["obj"], documentation: "Return an ASCII-only representation of an object."),
        .function(name: "bin", parameters: ["number"], documentation: "Return the binary representation of an integer."),
        .function(name: "bool", parameters: ["object=False"], documentation: "Returns True when the argument is true, False otherwise. The builtins True and False are the only two instances of the class bool. The class bool is a subclass of the class int, and cannot be subclassed."),
        .function(name: "breakpoint", parameters: ["*args", "**kws"], documentation: "Call sys.breakpointhook(*args, **kws). sys.breakpointhook() must accept whatever arguments are passed."),
        .function(name: "bytearray", parameters: [], documentation: "bytearray(iterable_of_ints) -> bytearray bytearray(string, encoding[, errors]) -> bytearray bytearray(bytes_or_buffer) -> mutable copy of bytes_or_buffer bytearray(int) -> bytes array of size given by the parameter initialized with null bytes bytearray() -> empty bytes array"),
        .function(name: "bytes", parameters: [], documentation: "bytes(iterable_of_ints) -> bytes bytes(string, encoding[, errors]) -> bytes bytes(bytes_or_buffer) -> immutable copy of bytes_or_buffer bytes(int) -> bytes object of size given by the parameter initialized with null bytes bytes() -> empty bytes object"),
        .function(name: "callable", parameters: ["obj"], documentation: "Return whether the object is callable (i.e., some kind of function)."),
        .function(name: "chr", parameters: ["i"], documentation: "Return a Unicode string of one character with ordinal i; 0 <= i <= 0x10ffff."),
        .function(name: "classmethod", parameters: ["function"], documentation: "Convert a function to be a class method."),
        .function(name: "compile", parameters: ["source", "filename", "mode", "flags=0", "dont_inherit=False", "optimize=-1", "_feature_version=-1"], documentation: "Compile source into a code object that can be executed by exec() or eval()."),
        .function(name: "complex", parameters: ["real=0", "imag=0"], documentation: "Create a complex number from a string or numbers."),
        .function(name: "delattr", parameters: ["obj", "name"], documentation: "Deletes the named attribute from the given object."),
        .function(name: "dict", parameters: [], documentation: "dict() -> new empty dictionary dict(mapping) -> new dictionary initialized from a mapping object's (key, value) pairs dict(iterable) -> new dictionary initialized as if via: d = {} for k, v in iterable: d[k] = v dict(**kwargs) -> new dictionary initialized with the name=value pairs in the keyword argument list. For example: dict(one=1, two=2)"),
        .function(name: "dir", parameters: [], documentation: "dir([object]) -> list of strings"),
        .function(name: "divmod", parameters: ["x", "y"], documentation: "Return the tuple (x//y, x%y). Invariant: div*y + mod == x."),
        .function(name: "enumerate", parameters: ["iterable", "start=0"], documentation: "Return an enumerate object."),
        .function(name: "eval", parameters: ["source", "globals=None", "locals=None"], documentation: "Evaluate the given source in the context of globals and locals."),
        .function(name: "exec", parameters: ["source", "globals=None", "locals=None", "closure=None"], documentation: "Execute the given source in the context of globals and locals."),
        .function(name: "filter", parameters: ["function", "iterable"], documentation: "Return an iterator yielding those items of iterable for which function(item) is true. If function is None, return the items that are true."),
        .function(name: "float", parameters: ["x=0"], documentation: "Convert a string or number to a floating-point number, if possible."),
        .function(name: "format", parameters: ["value", "format_spec=''"], documentation: "Return type(value).__format__(value, format_spec)"),
        .function(name: "frozenset", parameters: ["iterable=()"], documentation: "Build an immutable unordered collection of unique elements."),
        .function(name: "getattr", parameters: [], documentation: "getattr(object, name[, default]) -> value"),
        .function(name: "globals", parameters: [], documentation: "Return the dictionary containing the current scope's global variables."),
        .function(name: "hasattr", parameters: ["obj", "name"], documentation: "Return whether the object has an attribute with the given name."),
        .function(name: "hash", parameters: ["obj"], documentation: "Return the hash value for the given object."),
        .function(name: "help", parameters: [], documentation: "Define the builtin 'help'."),
        .function(name: "hex", parameters: ["number"], documentation: "Return the hexadecimal representation of an integer."),
        .function(name: "id", parameters: ["obj"], documentation: "Return the identity of an object."),
        .function(name: "input", parameters: ["prompt=''"], documentation: "Read a string from standard input. The trailing newline is stripped."),
        .function(name: "int", parameters: [], documentation: "int([x]) -> integer int(x, base=10) -> integer"),
        .function(name: "isinstance", parameters: ["obj", "class_or_tuple"], documentation: "Return whether an object is an instance of a class or of a subclass thereof."),
        .function(name: "issubclass", parameters: ["cls", "class_or_tuple"], documentation: "Return whether 'cls' is derived from another class or is the same class."),
        .function(name: "iter", parameters: [], documentation: "iter(iterable) -> iterator iter(callable, sentinel) -> iterator"),
        .function(name: "len", parameters: ["obj"], documentation: "Return the number of items in a container."),
        .function(name: "list", parameters: ["iterable=()"], documentation: "Built-in mutable sequence."),
        .function(name: "locals", parameters: [], documentation: "Return a dictionary containing the current scope's local variables."),
        .function(name: "map", parameters: ["function", "iterable", "*iterables"], documentation: "Make an iterator that computes the function using arguments from each of the iterables. Stops when the shortest iterable is exhausted."),
        .function(name: "max", parameters: [], documentation: "max(iterable, *[, default=obj, key=func]) -> value max(arg1, arg2, *args, *[, key=func]) -> value"),
        .function(name: "memoryview", parameters: ["object"], documentation: "Create a new memoryview object which references the given object."),
        .function(name: "min", parameters: [], documentation: "min(iterable, *[, default=obj, key=func]) -> value min(arg1, arg2, *args, *[, key=func]) -> value"),
        .function(name: "next", parameters: [], documentation: "next(iterator[, default])"),
        .function(name: "object", parameters: [], documentation: "The base class of the class hierarchy."),
        .function(name: "oct", parameters: ["number"], documentation: "Return the octal representation of an integer."),
        .function(name: "open", parameters: ["file", "mode='r'", "buffering=-1", "encoding=None", "errors=None", "newline=None", "closefd=True", "opener=None"], documentation: "Open file and return a stream. Raise OSError upon failure."),
        .function(name: "ord", parameters: ["character"], documentation: "Return the ordinal value of a character."),
        .function(name: "pow", parameters: ["base", "exp", "mod=None"], documentation: "Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments"),
        .function(name: "print", parameters: ["*args", "sep=' '", "end='
'", "file=None", "flush=False"], documentation: "Prints the values to a stream, or to sys.stdout by default."),
        .function(name: "property", parameters: ["fget=None", "fset=None", "fdel=None", "doc=None"], documentation: "Property attribute."),
        .function(name: "range", parameters: [], documentation: "range(stop) -> range object range(start, stop[, step]) -> range object"),
        .function(name: "repr", parameters: ["obj"], documentation: "Return the canonical string representation of the object."),
        .function(name: "reversed", parameters: ["sequence"], documentation: "Return a reverse iterator over the values of the given sequence."),
        .function(name: "round", parameters: ["number", "ndigits=None"], documentation: "Round a number to a given precision in decimal digits."),
        .function(name: "set", parameters: ["iterable=()"], documentation: "Build an unordered collection of unique elements."),
        .function(name: "setattr", parameters: ["obj", "name", "value"], documentation: "Sets the named attribute on the given object to the specified value."),
        .function(name: "slice", parameters: [], documentation: "slice(stop) slice(start, stop[, step])"),
        .function(name: "sorted", parameters: ["iterable", "key=None", "reverse=False"], documentation: "Return a new list containing all items from the iterable in ascending order."),
        .function(name: "staticmethod", parameters: ["function"], documentation: "Convert a function to be a static method."),
        .function(name: "str", parameters: [], documentation: "str(object='') -> str str(bytes_or_buffer[, encoding[, errors]]) -> str"),
        .function(name: "sum", parameters: ["iterable", "start=0"], documentation: "Return the sum of a 'start' value (default: 0) plus an iterable of numbers"),
        .function(name: "super", parameters: [], documentation: "super() -> same as super(__class__, <first argument>) super(type) -> unbound super object super(type, obj) -> bound super object; requires isinstance(obj, type) super(type, type2) -> bound super object; requires issubclass(type2, type) Typical use to call a cooperative superclass method: class C(B): def meth(self, arg):"),
        .function(name: "tuple", parameters: ["iterable=()"], documentation: "Built-in immutable sequence."),
        .function(name: "type", parameters: [], documentation: "type(object) -> the object's type type(name, bases, dict, **kwds) -> a new type"),
        .function(name: "vars", parameters: [], documentation: "vars([object]) -> dictionary"),
        .function(name: "zip", parameters: ["*iterables", "strict=False"], documentation: "The zip object yields n-length tuples, where n is the number of iterables passed as positional arguments to zip(). The i-th element in every tuple comes from the i-th iterable argument to zip(). This continues until the shortest argument is exhausted."),
    ]

    // MARK: - Str Methods
    /// Str type methods - for use when type inference determines an object is a str
    struct StringMethods {
        static let methods: [CompletionItem] = [
            .function(name: "capitalize", parameters: [], documentation: "Return a capitalized version of the string."),
            .function(name: "casefold", parameters: [], documentation: "Return a version of the string suitable for caseless comparisons."),
            .function(name: "center", parameters: ["width", "fillchar=' '"], documentation: "Return a centered string of length width."),
            .function(name: "count", parameters: [], documentation: "Return the number of non-overlapping occurrences of substring sub in string S[start:end]."),
            .function(name: "encode", parameters: ["encoding='utf-8'", "errors='strict'"], documentation: "Encode the string using the codec registered for encoding."),
            .function(name: "endswith", parameters: [], documentation: "Return True if the string ends with the specified suffix, False otherwise."),
            .function(name: "expandtabs", parameters: ["tabsize=8"], documentation: "Return a copy where all tab characters are expanded using spaces."),
            .function(name: "find", parameters: [], documentation: "Return the lowest index in S where substring sub is found, such that sub is contained within S[start:end]."),
            .function(name: "format", parameters: ["*args", "**kwargs"], documentation: "Return a formatted version of the string, using substitutions from args and kwargs. The substitutions are identified by braces ('{' and '}')."),
            .function(name: "format_map", parameters: ["mapping"], documentation: "Return a formatted version of the string, using substitutions from mapping. The substitutions are identified by braces ('{' and '}')."),
            .function(name: "index", parameters: [], documentation: "Return the lowest index in S where substring sub is found, such that sub is contained within S[start:end]."),
            .function(name: "isalnum", parameters: [], documentation: "Return True if the string is an alpha-numeric string, False otherwise."),
            .function(name: "isalpha", parameters: [], documentation: "Return True if the string is an alphabetic string, False otherwise."),
            .function(name: "isascii", parameters: [], documentation: "Return True if all characters in the string are ASCII, False otherwise."),
            .function(name: "isdecimal", parameters: [], documentation: "Return True if the string is a decimal string, False otherwise."),
            .function(name: "isdigit", parameters: [], documentation: "Return True if the string is a digit string, False otherwise."),
            .function(name: "isidentifier", parameters: [], documentation: "Return True if the string is a valid Python identifier, False otherwise."),
            .function(name: "islower", parameters: [], documentation: "Return True if the string is a lowercase string, False otherwise."),
            .function(name: "isnumeric", parameters: [], documentation: "Return True if the string is a numeric string, False otherwise."),
            .function(name: "isprintable", parameters: [], documentation: "Return True if all characters in the string are printable, False otherwise."),
            .function(name: "isspace", parameters: [], documentation: "Return True if the string is a whitespace string, False otherwise."),
            .function(name: "istitle", parameters: [], documentation: "Return True if the string is a title-cased string, False otherwise."),
            .function(name: "isupper", parameters: [], documentation: "Return True if the string is an uppercase string, False otherwise."),
            .function(name: "join", parameters: ["iterable"], documentation: "Concatenate any number of strings."),
            .function(name: "ljust", parameters: ["width", "fillchar=' '"], documentation: "Return a left-justified string of length width."),
            .function(name: "lower", parameters: [], documentation: "Return a copy of the string converted to lowercase."),
            .function(name: "lstrip", parameters: ["chars=None"], documentation: "Return a copy of the string with leading whitespace removed."),
            .function(name: "maketrans", parameters: [], documentation: "Return a translation table usable for str.translate()."),
            .function(name: "partition", parameters: ["sep"], documentation: "Partition the string into three parts using the given separator."),
            .function(name: "removeprefix", parameters: ["prefix"], documentation: "Return a str with the given prefix string removed if present."),
            .function(name: "removesuffix", parameters: ["suffix"], documentation: "Return a str with the given suffix string removed if present."),
            .function(name: "replace", parameters: ["old", "new", "count=-1"], documentation: "Return a copy with all occurrences of substring old replaced by new."),
            .function(name: "rfind", parameters: [], documentation: "Return the highest index in S where substring sub is found, such that sub is contained within S[start:end]."),
            .function(name: "rindex", parameters: [], documentation: "Return the highest index in S where substring sub is found, such that sub is contained within S[start:end]."),
            .function(name: "rjust", parameters: ["width", "fillchar=' '"], documentation: "Return a right-justified string of length width."),
            .function(name: "rpartition", parameters: ["sep"], documentation: "Partition the string into three parts using the given separator."),
            .function(name: "rsplit", parameters: ["sep=None", "maxsplit=-1"], documentation: "Return a list of the substrings in the string, using sep as the separator string."),
            .function(name: "rstrip", parameters: ["chars=None"], documentation: "Return a copy of the string with trailing whitespace removed."),
            .function(name: "split", parameters: ["sep=None", "maxsplit=-1"], documentation: "Return a list of the substrings in the string, using sep as the separator string."),
            .function(name: "splitlines", parameters: ["keepends=False"], documentation: "Return a list of the lines in the string, breaking at line boundaries."),
            .function(name: "startswith", parameters: [], documentation: "Return True if the string starts with the specified prefix, False otherwise."),
            .function(name: "strip", parameters: ["chars=None"], documentation: "Return a copy of the string with leading and trailing whitespace removed."),
            .function(name: "swapcase", parameters: [], documentation: "Convert uppercase characters to lowercase and lowercase characters to uppercase."),
            .function(name: "title", parameters: [], documentation: "Return a version of the string where each word is titlecased."),
            .function(name: "translate", parameters: ["table"], documentation: "Replace each character in the string using the given translation table."),
            .function(name: "upper", parameters: [], documentation: "Return a copy of the string converted to uppercase."),
            .function(name: "zfill", parameters: ["width"], documentation: "Pad a numeric string with zeros on the left, to fill a field of the given width."),
        ]
    }

    // MARK: - List Methods
    /// List type methods - for use when type inference determines an object is a list
    struct ListMethods {
        static let methods: [CompletionItem] = [
            .function(name: "append", parameters: ["object"], documentation: "Append object to the end of the list."),
            .function(name: "clear", parameters: [], documentation: "Remove all items from list."),
            .function(name: "copy", parameters: [], documentation: "Return a shallow copy of the list."),
            .function(name: "count", parameters: ["value"], documentation: "Return number of occurrences of value."),
            .function(name: "extend", parameters: ["iterable"], documentation: "Extend list by appending elements from the iterable."),
            .function(name: "index", parameters: ["value", "start=0", "stop=9223372036854775807"], documentation: "Return first index of value."),
            .function(name: "insert", parameters: ["index", "object"], documentation: "Insert object before index."),
            .function(name: "pop", parameters: ["index=-1"], documentation: "Remove and return item at index (default last)."),
            .function(name: "remove", parameters: ["value"], documentation: "Remove first occurrence of value."),
            .function(name: "reverse", parameters: [], documentation: "Reverse *IN PLACE*."),
            .function(name: "sort", parameters: ["key=None", "reverse=False"], documentation: "Sort the list in ascending order and return None."),
        ]
    }

    // MARK: - Dict Methods
    /// Dict type methods - for use when type inference determines an object is a dict
    struct DictMethods {
        static let methods: [CompletionItem] = [
            .function(name: "clear", parameters: [], documentation: "Remove all items from the dict."),
            .function(name: "copy", parameters: [], documentation: "Return a shallow copy of the dict."),
            .function(name: "fromkeys", parameters: ["iterable", "value=None"], documentation: "Create a new dictionary with keys from iterable and values set to value."),
            .function(name: "get", parameters: ["key", "default=None"], documentation: "Return the value for key if key is in the dictionary, else default."),
            .function(name: "items", parameters: [], documentation: "Return a set-like object providing a view on the dict's items."),
            .function(name: "keys", parameters: [], documentation: "Return a set-like object providing a view on the dict's keys."),
            .function(name: "pop", parameters: [], documentation: "D.pop(k[,d]) -> v, remove specified key and return the corresponding value."),
            .function(name: "popitem", parameters: [], documentation: "Remove and return a (key, value) pair as a 2-tuple."),
            .function(name: "setdefault", parameters: ["key", "default=None"], documentation: "Insert key with a value of default if key is not in the dictionary."),
            .function(name: "update", parameters: [], documentation: "D.update([E, ]**F) -> None. Update D from mapping/iterable E and F. If E is present and has a .keys() method, then does: for k in E.keys(): D[k] = E[k] If E is present and lacks a .keys() method, then does: for k, v in E: D[k] = v In either case, this is followed by: for k in F: D[k] = F[k]"),
            .function(name: "values", parameters: [], documentation: "Return an object providing a view on the dict's values."),
        ]
    }

    // MARK: - Set Methods
    /// Set type methods - for use when type inference determines an object is a set
    struct SetMethods {
        static let methods: [CompletionItem] = [
            .function(name: "add", parameters: ["object"], documentation: "Add an element to a set."),
            .function(name: "clear", parameters: [], documentation: "Remove all elements from this set."),
            .function(name: "copy", parameters: [], documentation: "Return a shallow copy of a set."),
            .function(name: "difference", parameters: ["*others"], documentation: "Return a new set with elements in the set that are not in the others."),
            .function(name: "difference_update", parameters: ["*others"], documentation: "Update the set, removing elements found in others."),
            .function(name: "discard", parameters: ["object"], documentation: "Remove an element from a set if it is a member."),
            .function(name: "intersection", parameters: ["*others"], documentation: "Return a new set with elements common to the set and all others."),
            .function(name: "intersection_update", parameters: ["*others"], documentation: "Update the set, keeping only elements found in it and all others."),
            .function(name: "isdisjoint", parameters: ["other"], documentation: "Return True if two sets have a null intersection."),
            .function(name: "issubset", parameters: ["other"], documentation: "Report whether another set contains this set."),
            .function(name: "issuperset", parameters: ["other"], documentation: "Report whether this set contains another set."),
            .function(name: "pop", parameters: [], documentation: "Remove and return an arbitrary set element."),
            .function(name: "remove", parameters: ["object"], documentation: "Remove an element from a set; it must be a member."),
            .function(name: "symmetric_difference", parameters: ["other"], documentation: "Return a new set with elements in either the set or other but not both."),
            .function(name: "symmetric_difference_update", parameters: ["other"], documentation: "Update the set, keeping only elements found in either set, but not in both."),
            .function(name: "union", parameters: ["*others"], documentation: "Return a new set with elements from the set and all others."),
            .function(name: "update", parameters: ["*others"], documentation: "Update the set, adding elements from all others."),
        ]
    }

    // MARK: - Frozenset Methods
    /// Frozenset type methods - for use when type inference determines an object is a frozenset
    struct FrozensetMethods {
        static let methods: [CompletionItem] = [
            .function(name: "copy", parameters: [], documentation: "Return a shallow copy of a set."),
            .function(name: "difference", parameters: ["*others"], documentation: "Return a new set with elements in the set that are not in the others."),
            .function(name: "intersection", parameters: ["*others"], documentation: "Return a new set with elements common to the set and all others."),
            .function(name: "isdisjoint", parameters: ["other"], documentation: "Return True if two sets have a null intersection."),
            .function(name: "issubset", parameters: ["other"], documentation: "Report whether another set contains this set."),
            .function(name: "issuperset", parameters: ["other"], documentation: "Report whether this set contains another set."),
            .function(name: "symmetric_difference", parameters: ["other"], documentation: "Return a new set with elements in either the set or other but not both."),
            .function(name: "union", parameters: ["*others"], documentation: "Return a new set with elements from the set and all others."),
        ]
    }

    // MARK: - Bytes Methods
    /// Bytes type methods - for use when type inference determines an object is a bytes
    struct BytesMethods {
        static let methods: [CompletionItem] = [
            .function(name: "capitalize", parameters: [], documentation: "B.capitalize() -> copy of B"),
            .function(name: "center", parameters: ["width", "fillchar=b' '"], documentation: "Return a centered string of length width."),
            .function(name: "count", parameters: [], documentation: "Return the number of non-overlapping occurrences of subsection 'sub' in bytes B[start:end]."),
            .function(name: "decode", parameters: ["encoding='utf-8'", "errors='strict'"], documentation: "Decode the bytes using the codec registered for encoding."),
            .function(name: "endswith", parameters: [], documentation: "Return True if the bytes ends with the specified suffix, False otherwise."),
            .function(name: "expandtabs", parameters: ["tabsize=8"], documentation: "Return a copy where all tab characters are expanded using spaces."),
            .function(name: "find", parameters: [], documentation: "Return the lowest index in B where subsection 'sub' is found, such that 'sub' is contained within B[start,end]."),
            .function(name: "fromhex", parameters: ["string"], documentation: "Create a bytes object from a string of hexadecimal numbers."),
            .function(name: "hex", parameters: [], documentation: "Create a string of hexadecimal numbers from a bytes object."),
            .function(name: "index", parameters: [], documentation: "Return the lowest index in B where subsection 'sub' is found, such that 'sub' is contained within B[start,end]."),
            .function(name: "isalnum", parameters: [], documentation: "B.isalnum() -> bool"),
            .function(name: "isalpha", parameters: [], documentation: "B.isalpha() -> bool"),
            .function(name: "isascii", parameters: [], documentation: "B.isascii() -> bool"),
            .function(name: "isdigit", parameters: [], documentation: "B.isdigit() -> bool"),
            .function(name: "islower", parameters: [], documentation: "B.islower() -> bool"),
            .function(name: "isspace", parameters: [], documentation: "B.isspace() -> bool"),
            .function(name: "istitle", parameters: [], documentation: "B.istitle() -> bool"),
            .function(name: "isupper", parameters: [], documentation: "B.isupper() -> bool"),
            .function(name: "join", parameters: ["iterable_of_bytes"], documentation: "Concatenate any number of bytes objects."),
            .function(name: "ljust", parameters: ["width", "fillchar=b' '"], documentation: "Return a left-justified string of length width."),
            .function(name: "lower", parameters: [], documentation: "B.lower() -> copy of B"),
            .function(name: "lstrip", parameters: ["bytes=None"], documentation: "Strip leading bytes contained in the argument."),
            .function(name: "maketrans", parameters: ["frm", "to"], documentation: "Return a translation table usable for the bytes or bytearray translate method."),
            .function(name: "partition", parameters: ["sep"], documentation: "Partition the bytes into three parts using the given separator."),
            .function(name: "removeprefix", parameters: ["prefix"], documentation: "Return a bytes object with the given prefix string removed if present."),
            .function(name: "removesuffix", parameters: ["suffix"], documentation: "Return a bytes object with the given suffix string removed if present."),
            .function(name: "replace", parameters: ["old", "new", "count=-1"], documentation: "Return a copy with all occurrences of substring old replaced by new."),
            .function(name: "rfind", parameters: [], documentation: "Return the highest index in B where subsection 'sub' is found, such that 'sub' is contained within B[start,end]."),
            .function(name: "rindex", parameters: [], documentation: "Return the highest index in B where subsection 'sub' is found, such that 'sub' is contained within B[start,end]."),
            .function(name: "rjust", parameters: ["width", "fillchar=b' '"], documentation: "Return a right-justified string of length width."),
            .function(name: "rpartition", parameters: ["sep"], documentation: "Partition the bytes into three parts using the given separator."),
            .function(name: "rsplit", parameters: ["sep=None", "maxsplit=-1"], documentation: "Return a list of the sections in the bytes, using sep as the delimiter."),
            .function(name: "rstrip", parameters: ["bytes=None"], documentation: "Strip trailing bytes contained in the argument."),
            .function(name: "split", parameters: ["sep=None", "maxsplit=-1"], documentation: "Return a list of the sections in the bytes, using sep as the delimiter."),
            .function(name: "splitlines", parameters: ["keepends=False"], documentation: "Return a list of the lines in the bytes, breaking at line boundaries."),
            .function(name: "startswith", parameters: [], documentation: "Return True if the bytes starts with the specified prefix, False otherwise."),
            .function(name: "strip", parameters: ["bytes=None"], documentation: "Strip leading and trailing bytes contained in the argument."),
            .function(name: "swapcase", parameters: [], documentation: "B.swapcase() -> copy of B"),
            .function(name: "title", parameters: [], documentation: "B.title() -> copy of B"),
            .function(name: "translate", parameters: ["table", "delete=b''"], documentation: "Return a copy with each character mapped by the given translation table."),
            .function(name: "upper", parameters: [], documentation: "B.upper() -> copy of B"),
            .function(name: "zfill", parameters: ["width"], documentation: "Pad a numeric string with zeros on the left, to fill a field of the given width."),
        ]
    }

    // MARK: - Bytearray Methods
    /// Bytearray type methods - for use when type inference determines an object is a bytearray
    struct BytearrayMethods {
        static let methods: [CompletionItem] = [
            .function(name: "append", parameters: ["item"], documentation: "Append a single item to the end of the bytearray."),
            .function(name: "capitalize", parameters: [], documentation: "B.capitalize() -> copy of B"),
            .function(name: "center", parameters: ["width", "fillchar=b' '"], documentation: "Return a centered string of length width."),
            .function(name: "clear", parameters: [], documentation: "Remove all items from the bytearray."),
            .function(name: "copy", parameters: [], documentation: "Return a copy of B."),
            .function(name: "count", parameters: [], documentation: "Return the number of non-overlapping occurrences of subsection 'sub' in bytes B[start:end]."),
            .function(name: "decode", parameters: ["encoding='utf-8'", "errors='strict'"], documentation: "Decode the bytearray using the codec registered for encoding."),
            .function(name: "endswith", parameters: [], documentation: "Return True if the bytearray ends with the specified suffix, False otherwise."),
            .function(name: "expandtabs", parameters: ["tabsize=8"], documentation: "Return a copy where all tab characters are expanded using spaces."),
            .function(name: "extend", parameters: ["iterable_of_ints"], documentation: "Append all the items from the iterator or sequence to the end of the bytearray."),
            .function(name: "find", parameters: [], documentation: "Return the lowest index in B where subsection 'sub' is found, such that 'sub' is contained within B[start:end]."),
            .function(name: "fromhex", parameters: ["string"], documentation: "Create a bytearray object from a string of hexadecimal numbers."),
            .function(name: "hex", parameters: [], documentation: "Create a string of hexadecimal numbers from a bytearray object."),
            .function(name: "index", parameters: [], documentation: "Return the lowest index in B where subsection 'sub' is found, such that 'sub' is contained within B[start:end]."),
            .function(name: "insert", parameters: ["index", "item"], documentation: "Insert a single item into the bytearray before the given index."),
            .function(name: "isalnum", parameters: [], documentation: "B.isalnum() -> bool"),
            .function(name: "isalpha", parameters: [], documentation: "B.isalpha() -> bool"),
            .function(name: "isascii", parameters: [], documentation: "B.isascii() -> bool"),
            .function(name: "isdigit", parameters: [], documentation: "B.isdigit() -> bool"),
            .function(name: "islower", parameters: [], documentation: "B.islower() -> bool"),
            .function(name: "isspace", parameters: [], documentation: "B.isspace() -> bool"),
            .function(name: "istitle", parameters: [], documentation: "B.istitle() -> bool"),
            .function(name: "isupper", parameters: [], documentation: "B.isupper() -> bool"),
            .function(name: "join", parameters: ["iterable_of_bytes"], documentation: "Concatenate any number of bytes/bytearray objects."),
            .function(name: "ljust", parameters: ["width", "fillchar=b' '"], documentation: "Return a left-justified string of length width."),
            .function(name: "lower", parameters: [], documentation: "B.lower() -> copy of B"),
            .function(name: "lstrip", parameters: ["bytes=None"], documentation: "Strip leading bytes contained in the argument."),
            .function(name: "maketrans", parameters: ["frm", "to"], documentation: "Return a translation table usable for the bytes or bytearray translate method."),
            .function(name: "partition", parameters: ["sep"], documentation: "Partition the bytearray into three parts using the given separator."),
            .function(name: "pop", parameters: ["index=-1"], documentation: "Remove and return a single item from B."),
            .function(name: "remove", parameters: ["value"], documentation: "Remove the first occurrence of a value in the bytearray."),
            .function(name: "removeprefix", parameters: ["prefix"], documentation: "Return a bytearray with the given prefix string removed if present."),
            .function(name: "removesuffix", parameters: ["suffix"], documentation: "Return a bytearray with the given suffix string removed if present."),
            .function(name: "replace", parameters: ["old", "new", "count=-1"], documentation: "Return a copy with all occurrences of substring old replaced by new."),
            .function(name: "reverse", parameters: [], documentation: "Reverse the order of the values in B in place."),
            .function(name: "rfind", parameters: [], documentation: "Return the highest index in B where subsection 'sub' is found, such that 'sub' is contained within B[start:end]."),
            .function(name: "rindex", parameters: [], documentation: "Return the highest index in B where subsection 'sub' is found, such that 'sub' is contained within B[start:end]."),
            .function(name: "rjust", parameters: ["width", "fillchar=b' '"], documentation: "Return a right-justified string of length width."),
            .function(name: "rpartition", parameters: ["sep"], documentation: "Partition the bytearray into three parts using the given separator."),
            .function(name: "rsplit", parameters: ["sep=None", "maxsplit=-1"], documentation: "Return a list of the sections in the bytearray, using sep as the delimiter."),
            .function(name: "rstrip", parameters: ["bytes=None"], documentation: "Strip trailing bytes contained in the argument."),
            .function(name: "split", parameters: ["sep=None", "maxsplit=-1"], documentation: "Return a list of the sections in the bytearray, using sep as the delimiter."),
            .function(name: "splitlines", parameters: ["keepends=False"], documentation: "Return a list of the lines in the bytearray, breaking at line boundaries."),
            .function(name: "startswith", parameters: [], documentation: "Return True if the bytearray starts with the specified prefix, False otherwise."),
            .function(name: "strip", parameters: ["bytes=None"], documentation: "Strip leading and trailing bytes contained in the argument."),
            .function(name: "swapcase", parameters: [], documentation: "B.swapcase() -> copy of B"),
            .function(name: "title", parameters: [], documentation: "B.title() -> copy of B"),
            .function(name: "translate", parameters: ["table", "delete=b''"], documentation: "Return a copy with each character mapped by the given translation table."),
            .function(name: "upper", parameters: [], documentation: "B.upper() -> copy of B"),
            .function(name: "zfill", parameters: ["width"], documentation: "Pad a numeric string with zeros on the left, to fill a field of the given width."),
        ]
    }

    // MARK: - Tuple Methods
    /// Tuple type methods - for use when type inference determines an object is a tuple
    struct TupleMethods {
        static let methods: [CompletionItem] = [
            .function(name: "count", parameters: ["value"], documentation: "Return number of occurrences of value."),
            .function(name: "index", parameters: ["value", "start=0", "stop=9223372036854775807"], documentation: "Return first index of value."),
        ]
    }

    // MARK: - Math Module
    private static let mathModuleCompletions: [CompletionItem] = [
        // Math module constants
        .constant(name: "math.e", value: "2.718281828459045", documentation: "Convert a string or number to a floating-point number, if possible."),
        .constant(name: "math.inf", value: "inf", documentation: "Convert a string or number to a floating-point number, if possible."),
        .constant(name: "math.nan", value: "nan", documentation: "Convert a string or number to a floating-point number, if possible."),
        .constant(name: "math.pi", value: "3.141592653589793", documentation: "Convert a string or number to a floating-point number, if possible."),
        .constant(name: "math.tau", value: "6.283185307179586", documentation: "Convert a string or number to a floating-point number, if possible."),

        // Math module functions
        .function(name: "math.acos", parameters: ["x"], documentation: "Return the arc cosine (measured in radians) of x."),
        .function(name: "math.acosh", parameters: ["x"], documentation: "Return the inverse hyperbolic cosine of x."),
        .function(name: "math.asin", parameters: ["x"], documentation: "Return the arc sine (measured in radians) of x."),
        .function(name: "math.asinh", parameters: ["x"], documentation: "Return the inverse hyperbolic sine of x."),
        .function(name: "math.atan", parameters: ["x"], documentation: "Return the arc tangent (measured in radians) of x."),
        .function(name: "math.atan2", parameters: ["y", "x"], documentation: "Return the arc tangent (measured in radians) of y/x."),
        .function(name: "math.atanh", parameters: ["x"], documentation: "Return the inverse hyperbolic tangent of x."),
        .function(name: "math.cbrt", parameters: ["x"], documentation: "Return the cube root of x."),
        .function(name: "math.ceil", parameters: ["x"], documentation: "Return the ceiling of x as an Integral."),
        .function(name: "math.comb", parameters: ["n", "k"], documentation: "Number of ways to choose k items from n items without repetition and without order."),
        .function(name: "math.copysign", parameters: ["x", "y"], documentation: "Return a float with the magnitude (absolute value) of x but the sign of y."),
        .function(name: "math.cos", parameters: ["x"], documentation: "Return the cosine of x (measured in radians)."),
        .function(name: "math.cosh", parameters: ["x"], documentation: "Return the hyperbolic cosine of x."),
        .function(name: "math.degrees", parameters: ["x"], documentation: "Convert angle x from radians to degrees."),
        .function(name: "math.dist", parameters: ["p", "q"], documentation: "Return the Euclidean distance between two points p and q."),
        .function(name: "math.erf", parameters: ["x"], documentation: "Error function at x."),
        .function(name: "math.erfc", parameters: ["x"], documentation: "Complementary error function at x."),
        .function(name: "math.exp", parameters: ["x"], documentation: "Return e raised to the power of x."),
        .function(name: "math.exp2", parameters: ["x"], documentation: "Return 2 raised to the power of x."),
        .function(name: "math.expm1", parameters: ["x"], documentation: "Return exp(x)-1."),
        .function(name: "math.fabs", parameters: ["x"], documentation: "Return the absolute value of the float x."),
        .function(name: "math.factorial", parameters: ["n"], documentation: "Find n!."),
        .function(name: "math.floor", parameters: ["x"], documentation: "Return the floor of x as an Integral."),
        .function(name: "math.fma", parameters: ["x", "y", "z"], documentation: "Fused multiply-add operation."),
        .function(name: "math.fmod", parameters: ["x", "y"], documentation: "Return fmod(x, y), according to platform C."),
        .function(name: "math.frexp", parameters: ["x"], documentation: "Return the mantissa and exponent of x, as pair (m, e)."),
        .function(name: "math.fsum", parameters: ["seq"], documentation: "Return an accurate floating-point sum of values in the iterable seq."),
        .function(name: "math.gamma", parameters: ["x"], documentation: "Gamma function at x."),
        .function(name: "math.gcd", parameters: ["*integers"], documentation: "Greatest Common Divisor."),
        .function(name: "math.hypot", parameters: [], documentation: "hypot(*coordinates) -> value"),
        .function(name: "math.isclose", parameters: ["a", "b", "rel_tol=1e-09", "abs_tol=0.0"], documentation: "Determine whether two floating-point numbers are close in value."),
        .function(name: "math.isfinite", parameters: ["x"], documentation: "Return True if x is neither an infinity nor a NaN, and False otherwise."),
        .function(name: "math.isinf", parameters: ["x"], documentation: "Return True if x is a positive or negative infinity, and False otherwise."),
        .function(name: "math.isnan", parameters: ["x"], documentation: "Return True if x is a NaN (not a number), and False otherwise."),
        .function(name: "math.isqrt", parameters: ["n"], documentation: "Return the integer part of the square root of the input."),
        .function(name: "math.lcm", parameters: ["*integers"], documentation: "Least Common Multiple."),
        .function(name: "math.ldexp", parameters: ["x", "i"], documentation: "Return x * (2**i)."),
        .function(name: "math.lgamma", parameters: ["x"], documentation: "Natural logarithm of absolute value of Gamma function at x."),
        .function(name: "math.log", parameters: [], documentation: "log(x, [base=math.e]) Return the logarithm of x to the given base."),
        .function(name: "math.log10", parameters: ["x"], documentation: "Return the base 10 logarithm of x."),
        .function(name: "math.log1p", parameters: ["x"], documentation: "Return the natural logarithm of 1+x (base e)."),
        .function(name: "math.log2", parameters: ["x"], documentation: "Return the base 2 logarithm of x."),
        .function(name: "math.modf", parameters: ["x"], documentation: "Return the fractional and integer parts of x."),
        .function(name: "math.nextafter", parameters: ["x", "y", "steps=None"], documentation: "Return the floating-point value the given number of steps after x towards y."),
        .function(name: "math.perm", parameters: ["n", "k=None"], documentation: "Number of ways to choose k items from n items without repetition and with order."),
        .function(name: "math.pow", parameters: ["x", "y"], documentation: "Return x**y (x to the power of y)."),
        .function(name: "math.prod", parameters: ["iterable", "start=1"], documentation: "Calculate the product of all the elements in the input iterable."),
        .function(name: "math.radians", parameters: ["x"], documentation: "Convert angle x from degrees to radians."),
        .function(name: "math.remainder", parameters: ["x", "y"], documentation: "Difference between x and the closest integer multiple of y."),
        .function(name: "math.sin", parameters: ["x"], documentation: "Return the sine of x (measured in radians)."),
        .function(name: "math.sinh", parameters: ["x"], documentation: "Return the hyperbolic sine of x."),
        .function(name: "math.sqrt", parameters: ["x"], documentation: "Return the square root of x."),
        .function(name: "math.sumprod", parameters: ["p", "q"], documentation: "Return the sum of products of values from two iterables p and q."),
        .function(name: "math.tan", parameters: ["x"], documentation: "Return the tangent of x (measured in radians)."),
        .function(name: "math.tanh", parameters: ["x"], documentation: "Return the hyperbolic tangent of x."),
        .function(name: "math.trunc", parameters: ["x"], documentation: "Truncates the Real x to the nearest Integral toward 0."),
        .function(name: "math.ulp", parameters: ["x"], documentation: "Return the value of the least significant bit of the float x."),
    ]
